import { Asset, Kind } from "./types";

export const STORAGE_KEY = "myassets.ledger.v1";

export const SEED_ASSETS: Asset[] = [
  {
    id: "seed-21st",
    title: "21st.dev component gallery",
    url: "https://21st.dev",
    kind: "component",
    category: "Design systems",
    tags: ["react", "ui", "gallery"],
    notes: "Searchable library of production React components.",
    favorite: true,
    createdAt: "2026-01-12T10:00:00.000Z",
    updatedAt: "2026-01-12T10:00:00.000Z",
  },
  {
    id: "seed-shadcn",
    title: "shadcn/ui",
    url: "https://ui.shadcn.com",
    kind: "component",
    category: "Design systems",
    tags: ["react", "radix", "tailwind"],
    notes: "Copy-paste primitives. Good baseline for dashboards.",
    favorite: true,
    createdAt: "2026-02-03T10:00:00.000Z",
    updatedAt: "2026-02-03T10:00:00.000Z",
  },
  {
    id: "seed-component-gallery",
    title: "Component Gallery",
    url: "https://component.gallery",
    kind: "component",
    category: "Buttons & forms",
    tags: ["patterns", "reference"],
    notes: "How real products implement common UI pieces.",
    favorite: false,
    createdAt: "2026-03-18T10:00:00.000Z",
    updatedAt: "2026-03-18T10:00:00.000Z",
  },
  {
    id: "seed-awwwards",
    title: "Awwwards",
    url: "https://www.awwwards.com",
    kind: "inspiration",
    category: "Landing pages",
    tags: ["sites", "motion", "awards"],
    notes: "Daily scan for layout and interaction ideas.",
    favorite: false,
    createdAt: "2026-04-02T10:00:00.000Z",
    updatedAt: "2026-04-02T10:00:00.000Z",
  },
  {
    id: "seed-godly",
    title: "Godly",
    url: "https://godly.website",
    kind: "inspiration",
    category: "Landing pages",
    tags: ["web", "curated"],
    notes: "Tight curation of distinctive marketing sites.",
    favorite: true,
    createdAt: "2026-04-21T10:00:00.000Z",
    updatedAt: "2026-04-21T10:00:00.000Z",
  },
  {
    id: "seed-mobbin",
    title: "Mobbin",
    url: "https://mobbin.com",
    kind: "mobile",
    category: "Native patterns",
    tags: ["ios", "android", "flows"],
    notes: "Screen flows from shipped apps. Use before inventing a pattern.",
    favorite: true,
    createdAt: "2026-05-09T10:00:00.000Z",
    updatedAt: "2026-05-09T10:00:00.000Z",
  },
  {
    id: "seed-ios",
    title: "Apple Human Interface Guidelines",
    url: "https://developer.apple.com/design/human-interface-guidelines",
    kind: "mobile",
    category: "Native patterns",
    tags: ["ios", "guidelines"],
    notes: "Source of truth for iOS spacing, nav, and controls.",
    favorite: false,
    createdAt: "2026-05-11T10:00:00.000Z",
    updatedAt: "2026-05-11T10:00:00.000Z",
  },
  {
    id: "seed-md3",
    title: "Material Design 3",
    url: "https://m3.material.io",
    kind: "mobile",
    category: "Design systems",
    tags: ["android", "material"],
    notes: "Android and cross-platform component language.",
    favorite: false,
    createdAt: "2026-05-14T10:00:00.000Z",
    updatedAt: "2026-05-14T10:00:00.000Z",
  },
  {
    id: "seed-mdn",
    title: "MDN Web Docs",
    url: "https://developer.mozilla.org",
    kind: "web",
    category: "Dev tools",
    tags: ["docs", "html", "css"],
    notes: "Canonical web platform reference.",
    favorite: false,
    createdAt: "2026-06-01T10:00:00.000Z",
    updatedAt: "2026-06-01T10:00:00.000Z",
  },
  {
    id: "seed-caniuse",
    title: "Can I use",
    url: "https://caniuse.com",
    kind: "web",
    category: "Dev tools",
    tags: ["browser", "support"],
    notes: "Check support before committing to a CSS feature.",
    favorite: false,
    createdAt: "2026-06-08T10:00:00.000Z",
    updatedAt: "2026-06-08T10:00:00.000Z",
  },
  {
    id: "seed-lucide",
    title: "Lucide icons",
    url: "https://lucide.dev",
    kind: "toolkit",
    category: "Icons",
    tags: ["icons", "svg"],
    notes: "Clean stroke set that scales well in product UI.",
    favorite: false,
    createdAt: "2026-07-02T10:00:00.000Z",
    updatedAt: "2026-07-02T10:00:00.000Z",
  },
  {
    id: "seed-fontshare",
    title: "Fontshare",
    url: "https://www.fontshare.com",
    kind: "toolkit",
    category: "Type & color",
    tags: ["type", "free"],
    notes: "Quality free type for product and marketing.",
    favorite: false,
    createdAt: "2026-07-19T10:00:00.000Z",
    updatedAt: "2026-07-19T10:00:00.000Z",
  },
];

export function isKind(value: string): value is Kind {
  return ["component", "inspiration", "web", "mobile", "toolkit"].includes(value);
}
